import { useCallback, useEffect, useRef, useState } from "react";
import type { AnswerOption, ContentData, FlowItem, PhantomQuestion, QuestionsData, Question, RedirectPage } from "../types";
import { clamp, pick } from "../data";
export interface Hud { score:number; realIndex:number; total:number; rage:number; streak:number; mood:string; achievements:string[]; corruption:number; }
export type Phase="name"|"question"|"phantom"|"redirect"|"result"|"secret";
export interface View { phase:Phase; current:FlowItem|null; reveal:"none"|"correct"|"wrong"; selectedId:string|null; hintShown:boolean; attempts:number; locked:boolean; feedback:"wrong"|"giveup"|null; redirectPages:RedirectPage[]; redirectIndex:number; phantomPicked:number; phantomTimeLeft:number; hud:Hud; result:ResultSummary|null; resetSeq:number; cheatUsed:boolean; }
export interface ResultSummary{ score:number; correctAnswers:number; total:number; wrongAnswers:number; bestStreak:number; rage:number; hintsUsed:number; noHintBonus:boolean; achievements:string[]; distribution:{a:number;b:number;c:number;d:number}; rank:string; rankColor:string; cheatUsed:boolean; }
interface S{ startedAt:number; flow:FlowItem[]; flowIndex:number; realIndex:number; attempts:number; score:number; correctAnswers:number; wrongAnswers:number; currentStreak:number; bestStreak:number; wrongStreak:number; rage:number; dCount:number; distribution:{a:number;b:number;c:number;d:number}; hintsUsed:number; noHintBonus:boolean; answersLog:{qid:number;dt:number;correct:boolean;attempts:number}[]; corruption:number; twistsShown:Record<number,boolean>; lastRealId:number|null; achievements:Record<string,boolean>; qStart:number; redirectPages:RedirectPage[]; redirectDone:(()=>void)|null; redirectIndex:number; noHintBonusApplied:boolean; cheatUsed:boolean; }
function initialState():S{return{startedAt:0,flow:[],flowIndex:0,realIndex:0,attempts:0,score:0,correctAnswers:0,wrongAnswers:0,currentStreak:0,bestStreak:0,wrongStreak:0,rage:0,dCount:0,distribution:{a:0,b:0,c:0,d:0},hintsUsed:0,noHintBonus:true,answersLog:[],corruption:0,twistsShown:{},lastRealId:null,achievements:{},qStart:0,redirectPages:[],redirectDone:null,redirectIndex:0,noHintBonusApplied:false,cheatUsed:false};}
function buildFlow(q:QuestionsData):FlowItem[]{ const f:FlowItem[]=[]; q.questions.forEach(item=>{f.push({type:"real",q:item}); q.phantomQuestions.forEach(p=>{if(p.injectAfter===item.id)f.push({type:"phantom",q:p});});}); return f;}
function moodLabel(r:number){ if(r<=25)return"CALM"; if(r<=50)return"IRRITATED"; if(r<=75)return"FUMING"; if(r<=90)return"UNSTABLE"; if(r<=99)return"CRITICAL"; return"MELTDOWN";}
export interface Engine{ view:View; start:(n:string)=>void; chooseAnswer:(id:string)=>void; retry:()=>void; giveUp:()=>void; useHint:()=>void; phantomSelect:(id:string)=>void; phantomNext:()=>void; nextRedirect:()=>void; reset:()=>void; markCheat:()=>void; }
export function useGame(questions:QuestionsData, content:ContentData, onSfx?:(k:string)=>void):Engine{
 const Sref=useRef<S>(initialState()); const questionsRef=useRef(questions); questionsRef.current=questions; const contentRef=useRef(content); contentRef.current=content; const sfxRef=useRef(onSfx); sfxRef.current=onSfx; const phantomTimer=useRef<ReturnType<typeof setInterval>|null>(null);
 const [view,setView]=useState<View>({phase:"name",current:null,reveal:"none",selectedId:null,hintShown:false,attempts:0,locked:false,feedback:null,redirectPages:[],redirectIndex:0,phantomPicked:0,phantomTimeLeft:30,hud:{score:0,realIndex:0,total:questionsRef.current.questions.length,rage:0,streak:0,mood:"CALM",achievements:[],corruption:0},result:null,resetSeq:0,cheatUsed:false});
 const syncHud=useCallback(():Hud=>{ const s=Sref.current; const prog=s.flow.length>0?(s.flowIndex/s.flow.length)*100:0; const corr=s.cheatUsed?100:Math.min(100,Math.round(prog+(s.rage>50?15:0)+(s.wrongStreak*3))); return{score:s.score,realIndex:s.realIndex,total:questionsRef.current.questions.length,rage:s.rage,streak:s.currentStreak,mood:moodLabel(s.rage),achievements:Object.keys(s.achievements),corruption:corr};},[]);
 const setPhaseView=useCallback((patch:Partial<View>)=>setView(v=>({...v,...patch,hud:syncHud()})),[syncHud]);
 const clearPhantomTimer=()=>{ if(phantomTimer.current){clearInterval(phantomTimer.current); phantomTimer.current=null;}};
 const showResults=useCallback(()=>{ const s=Sref.current; clearPhantomTimer(); const total=questionsRef.current.questions.length; if(s.correctAnswers===total&&s.hintsUsed===0&&!s.cheatUsed){ setPhaseView({phase:"secret"}); return;} let finalScore=s.score; let rank="BOYFRIEND NOVICE", rankColor="#56b4e9"; if(s.cheatUsed){ finalScore=-Math.abs(s.score)-500; const cr=["CERTIFIED FRAUD","BOYFRIEND IMPERSONATOR","ROMANCE SCAMMER","LORE CRIMINAL","DATING APP BANNED","BOYFRIEND RESTRAINING ORDER"]; rank=pick(cr); rankColor="#ff3860";} else { const pct=s.correctAnswers/total; if(pct>=0.9){rank="BOYFRIEND WHISPERER"; rankColor="#2ecc71";} else if(pct>=0.7){rank="BOYFRIEND SCHOLAR"; rankColor="#ff9900";} else if(pct>=0.5){rank="BOYFRIEND INTERN"; rankColor="#cc79a7";} else if(pct>=0.3){rank="BOYFRIEND SUSPECT"; rankColor="#ff3860";}} const r:ResultSummary={score:finalScore,correctAnswers:s.correctAnswers,total,wrongAnswers:s.wrongAnswers,bestStreak:s.bestStreak,rage:s.rage,hintsUsed:s.hintsUsed,noHintBonus:s.noHintBonus&&!s.cheatUsed,achievements:Object.keys(s.achievements),distribution:{...s.distribution},rank,rankColor,cheatUsed:s.cheatUsed}; setPhaseView({phase:"result",result:r});},[setPhaseView]);
 const renderCurrent=useCallback(()=>{ const s=Sref.current; const item=s.flow[s.flowIndex]; if(!item)return showResults(); if(item.type==="real"){ s.realIndex++; s.attempts=0; s.lastRealId=item.q.id; s.qStart=Date.now(); setPhaseView({phase:"question",current:item,reveal:"none",selectedId:null,hintShown:false,attempts:0,locked:false,feedback:null});} else { startPhantom(item.q);} },[setPhaseView,showResults]);
 const advanceFlow=useCallback(()=>{ const s=Sref.current; s.flowIndex++; setPhaseView({}); renderCurrent(); },[renderCurrent,setPhaseView]);
 const runRedirectChain=(pages:RedirectPage[],onDone:()=>void)=>{ const s=Sref.current; s.redirectPages=pages; s.redirectDone=onDone; s.redirectIndex=0; if(sfxRef.current)sfxRef.current("glitch"); setPhaseView({phase:"redirect",redirectPages:pages,redirectIndex:0}); };
 const loadingPage=():RedirectPage=>{ const s=Sref.current; let body:string; if(s.answersLog.length&&Math.random()<0.5){ const wrong=s.answersLog.filter(l=>!l.correct).length; const pool=[`ANALYZED ${wrong} WRONG ANSWER${wrong===1?"":"S"}...`,`PROCESSING ${s.answersLog.length} DECISION${s.answersLog.length===1?"":"S"} SO FAR...`,"CROSS-REFERENCING YOUR MISTAKES...",`ESTIMATING BOYFRIEND DISAPPOINTMENT: ${Math.min(99,wrong*7)}%`]; body=pick(pool);} else body=pick(contentRef.current.systemMessages as string[]); return{type:"loading",url:"boyfriend.exe/redirect",body}; };
 const dPatternPage=():RedirectPage|null=>{ const n=Sref.current.dCount; if(n===3)return{title:"PATTERN DETECTED",tone:"bad",body:"You have selected <b>D</b> three times.<br><br>Interesting.",btn:"CONTINUE"}; if(n===5)return{title:"D-ANSWER FREQUENCY: HIGH",tone:"bad",body:"You have selected <b>D</b> five times.<br>There are other buttons.<br>We checked.",btn:"CONTINUE"}; if(n===8)return{title:"THIS IS NO LONGER A COINCIDENCE",tone:"bad",body:"D D D D D D D D<br><br>ERROR<br>DISTRIBUTION TOO DENSE",btn:"CONTINUE"}; if(n===10)return{title:"WHAT ARE YOU DOING?",tone:"bad",body:"There are literally three other answers.",btn:"CONTINUE"}; if(n>=13)return{title:"CRITICAL ANSWER PATTERN",tone:"bad",body:"D D D D D D D D D D D D D<br><br>THE QUIZ HAS DEVELOPED A D-RELATED CONCERN.",btn:"CONTINUE"}; return null; };
 const buildCorrectPages=(q:Question,opt:AnswerOption,extra:string,dt:number|null):RedirectPage[]=>{ const s=Sref.current; const pages:RedirectPage[]=[loadingPage()]; if(opt&&opt.reaction)pages.push({title:opt.reaction.title,body:opt.reaction.body}); else { let type:string; if([3,5,10,15].includes(s.currentStreak))type="streak"; else type=pick(["praise","suspicious","lore","boyfriendReaction","dramatic","wholesome","fourthWall"]); if(type==="streak"){ const arr=(contentRef.current.correctReactions.streak||contentRef.current.correctScreens) as any[]; const i=s.currentStreak>=15?3:s.currentStreak>=10?2:s.currentStreak>=5?1:0; pages.push(arr[Math.min(i,arr.length-1)]);} else { const arr=(contentRef.current.correctReactions[type]||contentRef.current.correctScreens) as any[]; pages.push(pick(arr)); if(Math.random()<0.4)pages.push(pick(arr));}} if(dt!=null&&dt<2000)pages.push(pick(contentRef.current.timing.fast as any[])); if(extra)pages.push({title:"BY THE WAY",url:"boyfriend.exe/btw",body:extra,btn:"NOTED"}); pages.push({title:"CORRECT.",url:"boyfriend.exe/answer",body:(q.correctFeedback? q.correctFeedback+"<br>":"")+"<span class='subtle'>The boyfriend is mildly impressed. Try not to let it go to your head.</span>",btn:"NEXT QUESTION"}); pages.forEach(p=>p.tone="good"); return pages; };
 const buildWrongPages=(q:Question,opt:AnswerOption,dt:number|null):RedirectPage[]=>{ const s=Sref.current; const anger=clamp(s.wrongAnswers+s.wrongStreak,0,10); const pages:RedirectPage[]=[loadingPage()]; if(opt.reaction)pages.push({title:opt.reaction.title,body:opt.reaction.body}); else { const pool=anger<=2?["roast","short","fourthWall","boyfriendReaction","absurd","dramatic"]:anger<=5?["roast","fakeError","conspiracy","punishment","dramatic","boyfriendReaction","fakeTechnical"]:["conspiracy","punishment","dramatic","fakeTechnical","absurd","fakeError"]; const type=pick(pool); const arr=(contentRef.current.wrongReactions[type]||contentRef.current.wrongScreens) as any[]; pages.push(pick(arr)); if(Math.random()<0.5&&arr!==contentRef.current.wrongScreens)pages.push(pick(arr));} if(dt!=null){ if(dt<2000)pages.push(pick(contentRef.current.timing.fast as any[])); else if(dt>20000)pages.push(pick(contentRef.current.timing.slow as any[]));} if(s.wrongStreak>=3)pages.push(pick(contentRef.current.wrongStreak as any[])); if(anger>=4)pages.push({title:`ESCALATION ${anger}`,url:"boyfriend.exe/escalation",body:pick(contentRef.current.escalation as string[]),btn:"CONTINUE"}); pages.push({title:"ARE YOU SURE?",type:"choice",url:"boyfriend.exe/doubt",body:"That was wrong. Are you SURE it wasn't also wrong in a different way?"}); const correct=q.options.find(o=>o.correct)!; pages.push({title:"ANSWER (SINCE YOU ASKED)",url:"boyfriend.exe/answer",body:`The correct answer was: <b>${correct.text}</b><br><span class='subtle'>Try to keep up.</span>`,btn:"NEXT QUESTION"}); pages.forEach(p=>p.tone="bad"); return pages; };
 const chooseAnswer=useCallback((optId:string)=>{ const s=Sref.current; const item=s.flow[s.flowIndex]; if(!item||item.type!=="real")return; const q=item.q; const opt=q.options.find(o=>o.id===optId); if(!opt)return; if(opt.id==="d")s.dCount++; const dt=s.qStart?Date.now()-s.qStart:null; if(opt.correct)resolveCorrect(q,opt,dt); else resolveWrong(q,opt,dt);},[]);
 const resolveCorrect=(q:Question,opt:AnswerOption,dt:number|null)=>{ const s=Sref.current; s.attempts++; const pts=s.attempts===1?100:s.attempts===2?50:25; s.score+=pts; s.correctAnswers++; s.currentStreak++; if(s.currentStreak>s.bestStreak)s.bestStreak=s.currentStreak; s.wrongStreak=0; s.rage=Math.max(0,s.rage-3); s.distribution[opt.id as "a"|"b"|"c"|"d"]++; s.answersLog.push({qid:q.id,dt:dt??0,correct:true,attempts:s.attempts}); if(s.currentStreak===5)unlock("lore_master"); if(s.realIndex===1)unlock("cat_detective"); applyStreakBonus(); let extra=""; if(q.id===10&&s.distribution.d>=3)extra="<p class='conspiracy-line'><b>WAIT.</b></p><p class='conspiracy-line'>Why have you selected <b>D</b> three times in a row?</p>"; if(q.id===13)extra+="<p class='conspiracy-line'><b>ANSWER DISTRIBUTION ANALYSIS</b></p>"; const pages=buildCorrectPages(q,opt,extra,dt); const pp=dPatternPage(); if(pp)pages.unshift(pp); setPhaseView({reveal:"correct",selectedId:opt.id,locked:true}); if(sfxRef.current)sfxRef.current("correct"); setTimeout(()=>runRedirectChain(pages,advanceFlow),900); };
 const resolveWrong=(q:Question,opt:AnswerOption,dt:number|null)=>{ const s=Sref.current; s.attempts++; s.score=Math.max(0,s.score-15); s.rage+=8; s.wrongStreak++; s.currentStreak=0; s.answersLog.push({qid:q.id,dt:dt??0,correct:false,attempts:s.attempts}); if(s.wrongStreak===3)unlock("chaos_agent"); if(s.rage>=100)unlock("rage_machine"); if(s.attempts<=3){ setPhaseView({reveal:"wrong",selectedId:opt.id,locked:true,attempts:s.attempts,feedback:"wrong"}); if(sfxRef.current)sfxRef.current("wrong");} else { setPhaseView({reveal:"wrong",selectedId:opt.id,locked:true,feedback:"giveup"}); if(sfxRef.current)sfxRef.current("wrong"); setTimeout(()=>giveUp(q,opt,dt),700);} };
 const giveUp=(q:Question,_opt?:AnswerOption,dt:number|null=null)=>{ const s=Sref.current; s.wrongAnswers++; const pages=buildWrongPages(q,_opt as AnswerOption,dt); const pp=dPatternPage(); if(pp)pages.unshift(pp); runRedirectChain(pages,advanceFlow); };
 const useHint=useCallback(()=>{ const s=Sref.current; if(view.hintShown)return; const item=s.flow[s.flowIndex]; if(!item||item.type!=="real")return; s.hintsUsed++; s.noHintBonus=false; s.score=Math.max(0,s.score-20); s.rage+=2; setPhaseView({hintShown:true});},[view.hintShown,setPhaseView]);
 const retry=useCallback(()=>{ const s=Sref.current; s.score=Math.max(0,s.score-5); setPhaseView({reveal:"none",selectedId:null,locked:false,feedback:null,hintShown:false});},[setPhaseView]);
 const unlock=(id:string)=>{ const s=Sref.current; if(s.achievements[id])return; s.achievements[id]=true; setPhaseView({});};
 const applyStreakBonus=()=>{ const s=Sref.current; if(s.currentStreak===3)s.score+=100; else if(s.currentStreak===5)s.score+=250; else if(s.currentStreak===10)s.score+=500; else if(s.currentStreak===15)s.score+=1000;};
 const markCheat=useCallback(()=>{ Sref.current.cheatUsed=true; setPhaseView({cheatUsed:true});},[]);
 const startPhantom=(p:PhantomQuestion)=>{ clearPhantomTimer(); setPhaseView({phase:"phantom",current:{type:"phantom",q:p},reveal:"none",selectedId:null,phantomPicked:0,phantomTimeLeft:30}); let t=30; phantomTimer.current=setInterval(()=>{ t--; setView(v=>({...v,phantomTimeLeft:t,hud:syncHud()})); if(t<=0){ clearPhantomTimer(); const pages:RedirectPage[]=[{title:"TIME'S UP.",url:"boyfriend.exe/timeout",body:"There was never a correct answer. Of course. Moving on.",btn:"NEXT QUESTION"}]; runRedirectChain(pages,advanceFlow);} },1000); };
 const phantomSelect=useCallback((optId:string)=>{ const s=Sref.current; const item=s.flow[s.flowIndex]; if(!item||item.type!=="phantom")return; s.rage+=4; if(s.rage>=100)unlock("rage_machine"); setView(v=>{ const picked=v.phantomPicked+1; if(picked>=item.q.options.length)clearPhantomTimer(); return{...v,phantomPicked:picked,locked:picked>=item.q.options.length,hud:syncHud()};});},[]);
 const phantomNext=useCallback(()=>{ const s=Sref.current; const item=s.flow[s.flowIndex]; if(!item||item.type!=="phantom")return; s.score=Math.max(0,s.score-25); s.currentStreak=0; const pages:RedirectPage[]=[{type:"loading",url:"boyfriend.exe/void",body:"REDIRECTING YOU TO NOTHING"}]; const n=2+Math.floor(Math.random()*5); for(let k=0;k<n;k++){ const pg=(contentRef.current.wrongScreens[(k+7)%contentRef.current.wrongScreens.length] as any); pages.push({title:pg.title,body:pg.body,btn:"CONTINUE",type:pg.type,url:`boyfriend.exe/void/${200+k}`});} pages.push({title:"ANSWER: NONE",url:"boyfriend.exe/void/answer",body:item.q.reveal+"<br><span class='subtle'>(told you there was no correct answer.)</span>",btn:"NEXT QUESTION"}); runRedirectChain(pages,advanceFlow);},[]);
 const nextRedirect=()=>{ const s=Sref.current; const next=s.redirectIndex+1; if(next>=s.redirectPages.length){ const done=s.redirectDone; s.redirectPages=[]; s.redirectDone=null; s.redirectIndex=0; setPhaseView({phase:"question",redirectPages:[],redirectIndex:0}); if(done)done();} else { s.redirectIndex=next; setPhaseView({redirectIndex:next});}};
 const start=useCallback((name:string)=>{ const s=Sref.current; Object.assign(s,initialState()); s.flow=buildFlow(questions); s.startedAt=Date.now(); s.flowIndex=0; setPhaseView({resetSeq:view.resetSeq+1,result:null,cheatUsed:false}); renderCurrent();},[questions,renderCurrent,setPhaseView,view.resetSeq]);
 const reset=useCallback(()=>{ Object.assign(Sref.current,initialState()); clearPhantomTimer(); setView(v=>({...v,phase:"name",current:null,reveal:"none",selectedId:null,hintShown:false,attempts:0,locked:false,feedback:null,redirectPages:[],redirectIndex:0,phantomPicked:0,phantomTimeLeft:30,result:null,resetSeq:v.resetSeq+1,hud:syncHud(),cheatUsed:false}));},[syncHud]);
 useEffect(()=>()=>clearPhantomTimer(),[]);
 return{ view, start, chooseAnswer, retry, markCheat, giveUp:()=>{const s=Sref.current; const item=s.flow[s.flowIndex]; if(item&&item.type==="real")giveUp(item.q,undefined,null);}, useHint, phantomSelect, phantomNext, nextRedirect, reset, };
}
