import type { Playlist } from "./types";
const MUTE_KEY="boyfriendExeMuted"; const MUSIC_KEY="boyfriendExeTrack";
function readStorage(k:string){ try{return localStorage.getItem(k);}catch{return null;}}
function saveStorage(k:string,v:string){ try{localStorage.setItem(k,v);}catch{}}
const SFX_MANIFEST:Record<string,string>={ click:"assets/audio/answersSound.mp3", reveal:"assets/audio/show.mp3", select:"assets/audio/answersSound.mp3", correct:"assets/audio/first.mp3", wrong:"assets/audio/boump.mp3", error:"assets/audio/boump.mp3", glitch:"assets/audio/snearRoll.mp3", tense:"assets/audio/snearRoll.mp3", results:"assets/audio/results.mp3", };
const SFX_CACHE:Record<string,HTMLAudioElement>={}; const SFX_FAILED:Record<string,boolean>={}; const ACTIVE_AUDIO:HTMLAudioElement[]=[];
function loadSfx(n:string){ if(SFX_CACHE[n])return SFX_CACHE[n]; if(SFX_FAILED[n])return null; const u=SFX_MANIFEST[n]; if(!u)return null; const el=new Audio(u); el.preload="auto"; el.addEventListener("error",()=>{SFX_FAILED[n]=true;}); SFX_CACHE[n]=el; return el; }
function trackAudio(el:HTMLAudioElement){ if(ACTIVE_AUDIO.indexOf(el)===-1)ACTIVE_AUDIO.push(el); el.addEventListener("ended",()=>{const i=ACTIVE_AUDIO.indexOf(el); if(i!==-1)ACTIVE_AUDIO.splice(i,1);},{once:true}); return el; }
function stopAll(){ const all=[...ACTIVE_AUDIO]; Object.values(SFX_CACHE).forEach(el=>{if(all.indexOf(el)===-1)all.push(el);}); all.forEach(el=>{try{el.pause();el.currentTime=0;}catch{}}); ACTIVE_AUDIO.length=0; }
let audioCtx:AudioContext|null=null;
function getCtx(){ if(typeof window==="undefined")return null; try{ if(!audioCtx){const AC=(window as any).AudioContext||(window as any).webkitAudioContext; if(AC)audioCtx=new AC();} if(audioCtx&&audioCtx.state==="suspended")audioCtx.resume().catch(()=>{});}catch{} return audioCtx; }
const SYNTH_PRESETS:Record<string,{f:number;type:OscillatorType;d:number}>={ click:{f:520,type:"square",d:0.06}, correct:{f:740,type:"triangle",d:0.18}, wrong:{f:120,type:"sawtooth",d:0.22}, error:{f:90,type:"sawtooth",d:0.3}, glitch:{f:300,type:"square",d:0.12}, reveal:{f:420,type:"sine",d:0.1}, tense:{f:300,type:"triangle",d:0.1}, results:{f:600,type:"triangle",d:0.4}, };
function synthSfx(k:string){ const c=getCtx(); if(!c)return; const p=SYNTH_PRESETS[k]||SYNTH_PRESETS.click; try{const o=c.createOscillator();const g=c.createGain();o.connect(g);g.connect(c.destination);const t=c.currentTime; o.type=p.type; o.frequency.setValueAtTime(p.f,t); if(k==="wrong"||k==="error")o.frequency.exponentialRampToValueAtTime(40,t+p.d); if(k==="correct")o.frequency.exponentialRampToValueAtTime(1200,t+p.d); g.gain.setValueAtTime(0.18,t); g.gain.exponentialRampToValueAtTime(0.001,t+p.d); o.start(t);o.stop(t+p.d);}catch{}}
export function sfx(k:string){ if(readStorage(MUTE_KEY)==="1")return; const el=loadSfx(k); if(el){try{trackAudio(el);el.currentTime=0; const pr=el.play(); if(pr&&pr.catch)pr.catch(()=>{if(readStorage(MUTE_KEY)!=="1")synthSfx(k);}); return;}catch{}} synthSfx(k); }
export interface MusicManager{ start:()=>void; stop:()=>void; toggle:()=>boolean; get muted():boolean; current:()=>string; next:()=>void; previous:()=>void; selectTrack:(id:string)=>void; getPlaylist:()=>{id:string;title:string}[]; }
export function createMusicManager(playlist:Playlist):MusicManager{ const enabled=playlist.tracks.filter(t=>t.enabled!==false); const saved=readStorage(MUSIC_KEY); let idx=Math.max(0,enabled.findIndex(t=>t.id===saved)); if(idx<0)idx=Math.max(0,enabled.findIndex(t=>t.id===playlist.defaultTrack)); if(idx<0)idx=0; let el:HTMLAudioElement|null=null; let _muted=readStorage(MUTE_KEY)==="1"; let wanted=false; const play=()=>{ if(_muted||!enabled.length)return; const tr=enabled[idx%enabled.length]; if(!tr)return; if(el){try{el.pause();el.currentTime=0;}catch{}} el=new Audio(tr.file); el.preload="auto"; el.loop=false; el.volume=0.35; el.addEventListener("ended",()=>{ if(!_muted&&wanted){idx=(idx+1)%enabled.length; play();}}); el.addEventListener("error",()=>{ if(wanted&&enabled.length>1){idx=(idx+1)%enabled.length; play();}}); const pr=el.play(); if(pr&&pr.catch)pr.catch(()=>{});}; const persistTrack=()=>{const t=enabled[idx%enabled.length]; if(t)saveStorage(MUSIC_KEY,t.id);}; const persistMute=()=>saveStorage(MUTE_KEY,_muted?"1":"0"); return{ start(){wanted=true;play();}, stop(){wanted=false; if(el){try{el.pause();el.currentTime=0;}catch{}}}, toggle(){_muted=!_muted;persistMute(); if(_muted)stopAll(); else if(wanted)play(); return _muted;}, get muted(){return _muted;}, current(){return enabled[idx%enabled.length]?.title??"";}, next(){if(!enabled.length)return; idx=(idx+1)%enabled.length; persistTrack(); if(wanted&&!_muted)play();}, previous(){if(!enabled.length)return; idx=(idx-1+enabled.length)%enabled.length; persistTrack(); if(wanted&&!_muted)play();}, selectTrack(id:string){const i=enabled.findIndex(t=>t.id===id); if(i<0)return; idx=i; persistTrack(); if(wanted&&!_muted)play();}, getPlaylist(){return enabled.map(t=>({id:t.id,title:t.artist? t.title+" — "+t.artist:t.title}));}, };}
